services:

  academy-portal.announcement:
    image: academy-portal.announcement
    container_name: academy-portal.announcement
    build:
      context: .
      dockerfile: ./dockerfile
    restart: always
    ports:
      - "5005:5005"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:latest
    container_name: postgres_announcement
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: announcement
      PGDATA: /var/lib/postgresql/data/PGDATA
    ports:
      - "5430:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d announcement"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  pgdata:
    driver: local